---
- hosts: localhost
  connection: local
  tasks:
    - name: Get facts for one virtual network
      azure_rm_virtualnetwork_facts:
      register: network_fact

    - debug:
        var: network_fact

#    - debug:
#        var: azure_publicipaddresses
